wl-52624: Save 'regular' SDK files. +review WL-52131
wellnessliving/wl-sdk pull request #188
Opened 2024-04-03 13:37 UTC by DemienDM

2024-04-04 14:38 UTC, Kasp42 requested changes

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Profile/Edit/EditByTokenModel.php
> +   * @field class
SDK does not support this tag.

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Schedule/ScheduleList/StaffApp/ScheduleListModel.php
> +   *
Missing link to Sid class

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Staff/StaffElementModel.php
> +   * ID of the default system role.
Is it expected that this was deleted?

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Video/VideoElementModel.php
> +   * Method {@link VideoElementModel::_fileVideoGet()} will not return the result.
Method does not exist in SDK

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Video/VideoListModel.php
> +   * Sort order ID. `null` or 0 if order is undefined and depends on sort order.
Missing link to Sid class

2024-04-04 14:38 UTC, Kasp42 commented on WellnessLiving/Wl/Video/Watch/WatchModel.php
> -   * @see \WellnessLiving\Wl\Video\Watch\WatchSourceSid
Is it expected that this was deleted?

2024-04-23 12:33 UTC, DemienDM commented on WellnessLiving/Social/Facebook/Login/LoginModel.php
> -   * Use the application credential from the {@link \WellnessLiving\Core\Request\Model\Application\Credential\FacebookCredential} class for user authorization.
This class is not part of SDK and will not be added.

2024-04-23 12:33 UTC, DemienDM commented on WellnessLiving/Core/Request/Api/Application/Credential/CredentialModel.php
> +   *
This class is not part of SDK and will not be added.

2024-04-23 12:34 UTC, DemienDM commented on WellnessLiving/Social/Google/Plus/LoginModel.php
> -   * {@link \WellnessLiving\Core\Request\Model\Application\Credential\GoogleCredential} for user authorization.
This class is not part of SDK and will not be added.

2024-04-23 12:35 UTC, DemienDM commented on WellnessLiving/Wl/Appointment/Book/Finish/FinishMultipleModel.php
> -   * The structure of this array corresponds with the structure of {@link RsPayForm::$a_pay_source}.
This class is not part of SDK and will not be added.

2024-04-23 12:35 UTC, DemienDM commented on WellnessLiving/Wl/Appointment/Book/Purchase/PurchaseModel.php
> -   * In case this value is not specified returned image will have default thumbnail size {@link RsLoginLogo::THUMBNAIL_HEIGHT}.
This class is not part of SDK and will not be added.

2024-04-23 12:36 UTC, DemienDM commented on WellnessLiving/Wl/Appointment/Book/Purchase/PurchaseModel.php
> -   * In case this value is not specified returned image will have default thumbnail size {@link RsLoginLogo::THUMBNAIL_WIDTH}.
This class is not part of SDK and will not be added.

2024-04-23 12:36 UTC, DemienDM commented on WellnessLiving/Wl/Book/Process/Quiz/QuizModel.php
> -   * {@link Wl\Quiz\Response\QuizResponse::RESPONSE_SKIP} constant.
This class is not part of SDK and will not be added.

2024-04-23 12:51 UTC, DemienDM commented on WellnessLiving/Wl/Login/Promotion/PromotionPayPauseModel.php
> -   * {@link Wl\Promotion\Pay\PromotionPayPause::DATE_END_INDEFINITE} to make the period indefinite until further action.
This class is not part of SDK and will not be added.

2024-04-23 13:14 UTC, DemienDM commented on WellnessLiving/Social/Microsoft/LoginModel.php
> +   *
Here and further.
It was decided to not clean the blank lines in the documentation that were created after deleting the sentences.

2024-05-16 14:21 UTC, merged